### ISSUE TITLE
Setup MailChimp account

### ISSUE THREAD

**Issue by gotoplanb** [c4gnv/c4gnv.github.io#16]

**Comment by hollymariegibbs** [comment]
do we have a Mailchimp account? If not, should I set one up? What credentials should I use? @mikethefab

**Comment by mikethefab** [comment]
codeforgainesville@gmail.com
password: PolicemanBeautiful4SpellDiameter!

**Comment by hollymariegibbs** [comment]
snort.

**Comment by hollymariegibbs** [comment]
@mikethefab can you approve the confirmation for MailChimp that was sent to our gmail please? :)

**Comment by mikethefab** [comment]
Done.

**Comment by hollymariegibbs** [comment]
OK, we're good here. Closing ticket.
