### ISSUE TITLE
Gather list of other groups/meetups/networks that we can promote to

### ISSUE THREAD

**Issue by gotoplanb** [c4gnv/c4gnv.github.io#17]
- [ ] Studiocode
- [ ] GirlDevelopIt
- [ ] BarCamp
- [ ] ?

**Comment by samanthawolfe** [comment]
@hollymariegibbs Attendee contact list from the city's first hackathon in 2/2014.
[Attendee List.xlsx](https://github.com/c4gnv/c4gnv.github.io/files/284939/Attendee.List.xlsx)

**Comment by samanthawolfe** [comment]
@hollymariegibbs Patty Lipka at the Cade Museum is forming a Code for Girls local group to teach young and mostly at-risk girls about software development plipka@cademuseum.org
I'll also send her a personal email.

**Comment by hollymariegibbs** [comment]
@samanthawolfe any word from Patty Lipka?

**Comment by samanthawolfe** [comment]
@hollymariegibbs No; actually just sent her the personal invite.... Kinda forgot :(

**Comment by hollymariegibbs** [comment]
Is "Code for Girls" this? https://girlswhocode.com/

I just want to make sure it's different from Girl Develop It https://www.girldevelopit.com/

**Comment by hollymariegibbs** [comment]
- [ ] Hacker House
- [ ] Launchpad
- [ ] Starter Space
- [ ] 352 Media Group
- [ ] SharpSpring
- [ ] Shadow Health
- [ ] Mindtree
- [ ] Innovation Hub
- [ ] Gainesville CRA?

**Comment by samanthawolfe** [comment]
@hollymariegibbs Connected with Patty by email. Sounds like its Girls Who Code (you're first link). The Cade is partnering with Women Who Code from UF this summer. Their first class begins in late June, so sounds like they may start to plug in during the July event.

**Comment by samanthawolfe** [comment]
GCRA contact: Nathalie McCrate mccratena@cityofgainesville.org
