### ISSUE TITLE
C4GNV kickoff deck

### ISSUE THREAD

**Issue by gotoplanb** [c4gnv/c4gnv.github.io#2]
10-minute max presentation on the mission of C4GNV and the people involved.

## Specs

* 10-minute maximum
* Mission of C4GNV
* Code of Conduct
* How to communicate with the core team
* Upcoming events

## Tasks

- [x] create deck
- [x] show to core team
- [x] revise deck
- [x] upload to drive and link from this ticket

**Comment by ambercabrera** [comment]
[bit.do/NDoCH-deck](url)

**Comment by ambercabrera** [comment]
[bit.do/NDoCH-deck](url)

**Comment by ambercabrera** [comment]
[bit.do/gnv-NDoCH-deck](url)

**Comment by ambercabrera** [comment]
[bit.do/gnv-NDoCH-deck](url)

**Comment by ambercabrera** [comment]
[bit.do/gnv-NDoCH-deck](url)

**Comment by gotoplanb** [comment]
@ambercabrera Awesome stuff! I added some comments inline. I'm thinking we can work through a couple items together Tuesday morning, and then get the rest of the info from the core team during standup.

**Comment by ambercabrera** [comment]
Sounds good!

**Comment by gotoplanb** [comment]
@ambercabrera We made some small changes. Consider deck done!
