### ISSUE TITLE
NDoCH Agenda

### ISSUE THREAD

**Issue by ambercabrera** [c4gnv/c4gnv.github.io#21]
- [x] Create draft agenda

- [x] Submit to team for ideas and revisions

- [x] Add link to final agenda here

**Comment by gotoplanb** [comment]
@ambercabrera Looks great! Nothing seems amiss, and I really liked the idea of some breakouts for topics we often assume are understood (GitHub, civic hacking, etc.)

**Comment by ambercabrera** [comment]
bit.do/NDoCH-agenda2016
