### ISSUE TITLE
Post an update to the Meetup group that gets people ready for the day

### ISSUE THREAD

**Issue by gotoplanb** [c4gnv/c4gnv.github.io#24]
- where to park
- what to bring
- drinks and finger sandwiches will be provided
- Come with an idea of how you'd like to spend your time:
-- link to NDoCH for people to think if any of the stuff is interesting
-- Business Portal
-- Brainstorm for how we might connect kids and underserved communities to the city

**Comment by hollymariegibbs** [comment]
Yo, let me get those meetup credentials @gotoplanb  or @mikethefab or whoever has them

**Comment by hollymariegibbs** [comment]
Is there a place where we are holding our login credentials that we can access securely? @mikethefab @gotoplanb

**Comment by gotoplanb** [comment]
Not yet but make me a ticket for secure key management, and I'll explore options. I have something in mind.

**Comment by gotoplanb** [comment]
Done
