### ISSUE TITLE
find interns

### ISSUE THREAD

**Issue by gotoplanb** [c4gnv/c4gnv.github.io#25]

**Comment by hollymariegibbs** [comment]
Some dates:

**Career Showcase
September 27 & 28, 2016 | 9 a.m. – 3 p.m. | SW Recreation Center**
Hundreds of employers will be at our fall event looking to fill opportunities from internships to full-time positions. Where ever your interests lie, there’s a variety of employers from diverse industries who have come to the University of Florida to network with students just like you. Make sure to bring your Gator1 ID card!
