### ISSUE TITLE
setup gmail forwarding rule

### ISSUE THREAD

**Issue by gotoplanb** [c4gnv/c4gnv.github.io#26]
codeforgainesville+name@gmail.com should forward to personal email

**Comment by hollymariegibbs** [comment]
please use hello.hmg@gmail.com for my forwarding address

**Comment by mikethefab** [comment]
Can each of you please paste your preferred email address on this thread?

**Comment by Opeola** [comment]
opeenfeu@gmail.com please!

**Comment by samanthawolfe** [comment]
samantha.b.wolfe@gmail.com
