### ISSUE TITLE
Review admin site designs

### ISSUE THREAD

**Issue by hollymariegibbs** [c4gnv/c4gnv.github.io#48]
Hey there, team! Please take a look at the visual designs I've put together for our c4gnv.com site and leave your feedback here. 

Home: https://www.dropbox.com/s/lccvsow6gdfew1m/home.png?dl=0

Get Started: https://www.dropbox.com/s/twa0av2v33fcqjc/get-started.png?dl=0

**Comment by gotoplanb** [comment]
![get-started](https://cloud.githubusercontent.com/assets/51855/21657911/6cfa044c-d292-11e6-9a4c-5a091c296734.png)
![home](https://cloud.githubusercontent.com/assets/51855/21657913/6d141724-d292-11e6-8557-6d52dec92402.png)

**Comment by gotoplanb** [comment]
@hollymariegibbs Here be my suggestions:

## "getting started" looks wonderful.

- Add a "your idea" to step6. 
- Include a step0 link to view/read video/presentation/kickoff.
- Include code of conduct in the step0.

## "home" seems more like an "about" page. Perhaps move code of conduct to "getting started"

- Add activity feeds to home. GitHub, Meetup, Twitter active etc.

**Comment by hollymariegibbs** [comment]
- I'm wondering if we should make 'Getting Started' act as the homepage and 'About' as a sub-page? Thoughts?
- I am going to address "Your Idea" in what will now be step 2.
- Code of Conduct will be on both pages. I think the redundancy is good, but open to suggestions if you all think it should be removed.

**Comment by hollymariegibbs** [comment]
Revised comps:

![home](https://cloud.githubusercontent.com/assets/1693577/21686515/bac4d61a-d333-11e6-851a-3ab5cc198624.png)

![about](https://cloud.githubusercontent.com/assets/1693577/21686521/bf0c3dbc-d333-11e6-9fe1-f64046fe0e11.png)

**Comment by gotoplanb** [comment]
@hollymariegibbs Revised "home" looks fabulous. For "about", the mailing list signup needs a button to submit the form. Otherwise looks fly af.

**Comment by hollymariegibbs** [comment]
![about](https://cloud.githubusercontent.com/assets/1693577/22048897/02079a0c-dcfe-11e6-93dd-a1c2fcbb1e29.png)

Updated design, now with button! Closing ticket.
